spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loldiary
    username: root
    password: fkeldh97~
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    com.example.LOLDiary: DEBUG

riot:
  api: RGAPI-e739811a-a0bc-49e0-bcb1-c3ce63192436

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "Abcd1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect